apiVersion: charts.helm.k8s.io/v1alpha1
kind: CertManager
metadata:
  name: example-certmanager
spec:
  # Default values copied from <project_dir>/helm-charts/cert-manager/values.yaml
  
  affinity: {}
  cainjector:
    affinity: {}
    enabled: true
    extraArgs: []
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-cainjector
    nodeSelector: {}
    replicaCount: 1
    resources: {}
    securityContext: {}
    serviceAccount:
      create: true
    strategy: {}
    tolerations: []
  clusterResourceNamespace: ""
  extraArgs: []
  extraEnv: []
  featureGates: ""
  global:
    imagePullSecrets: []
    leaderElection:
      namespace: kube-system
    logLevel: 2
    podSecurityPolicy:
      enabled: false
      useAppArmor: true
    priorityClassName: ""
    rbac:
      create: true
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/jetstack/cert-manager-controller
  ingressShim: {}
  installCRDs: false
  nodeSelector: {}
  podLabels: {}
  prometheus:
    enabled: true
    servicemonitor:
      enabled: false
      interval: 60s
      labels: {}
      path: /metrics
      prometheusInstance: default
      scrapeTimeout: 30s
      targetPort: 9402
  replicaCount: 1
  resources: {}
  securityContext: {}
  serviceAccount:
    create: true
  strategy: {}
  tolerations: []
  volumeMounts: []
  volumes: []
  webhook:
    affinity: {}
    extraArgs: []
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-webhook
    nodeSelector: {}
    replicaCount: 1
    resources: {}
    securePort: 10250
    securityContext: {}
    serviceAccount:
      create: true
    strategy: {}
    tolerations: []
  
