apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: certmanager-operator
rules:

# Allow creating API Registration
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["apiservices"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow creating Audit Registration
- apiGroups: ["auditregistration.k8s.io"]
  resources: ["auditsinks"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow creating CRDs
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions on Prometheus Operator Service Monitor CRD
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions on Kubernetes Event
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions on Kubernetes Endpoint
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

# Allow actions on Kubernetes Cluster Role and Cluster Role Binding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions on Kubernetes Role and Role Binding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions for certmanager-operator

- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "update", "delete", "patch"]

- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["extensions"]
  resources: ["ingresses/finalizers"]
  verbs: ["update"]

- apiGroups: ["charts.helm.k8s.io"]
  resources: ["certmanagers", "certmanagers/status"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["orders"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["orders/status"]
  verbs: ["update"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["orders/finalizers"]
  verbs: ["update"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges/status"]
  verbs: ["update"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges/finalizers"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch", "deletecollection"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests/status"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests/finalizers"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch", "deletecollection"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificates/status"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["certificates/finalizers"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch", "deletecolleciton"]

- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers/status"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers/finalizers"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["issuers"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch", "deletecollection"]

- apiGroups: ["cert-manager.io"]
  resources: ["issuers/status"]
  verbs: ["update"]

- apiGroups: ["cert-manager.io"]
  resources: ["issuers/finalizers"]
  verbs: ["update"]

- apiGroups: ["route.openshift.io"]
  resources: ["routes/custom-host"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]