apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: certmanager-operator
rules:

# Allowed actions on Pods
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allowed actions on apps
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allowed actions on batch
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allowed actions on Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allowed actions on Secrets
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow all actions on Service Accounts
- apiGroups: [""]
  resources: ["serviceaccounts", "serviceaccounts/token"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow all for Role and Role Binding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allow actions for Namespace
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

# Allowed actions on PodDisruptionBudget Policy
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# Allowed actions on Finalizer
- apiGroups: ["apps"]
  resourceNames: ["certmanager-operator"]
  resources: ["daemonsets/finalizers", "deployments/finalizers", "statefulsets/finalizers"]
  verbs: ["update"]

